name: Build Prensa on push
# Este fluxo de trabalho é acionado em pushes para o repositório.
on: [push]

jobs:
  build-sass-theme:
    name: Build Prensa SCSS and JS
    runs-on: ubuntu-latest
    steps:
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
        
      - name: Git config and merge
        run: |
          git config --global user.name "Giovanni"
          git config --global user.email "giovanni@xproglabs.com"
          git config pull.ff only
          git checkout develop
          git branch temp

      - name: Check for merge
        run: git merge ${GITHUB_REF##*/} -m "merge"

      - name: Install packages
        run: npm install
          
      - name: Create destination for compiled CSS
        run: mkdir -vp /tmp/xprog-designsystem/css

      - name: Compile SCSS Theme
        uses: gha-utilities/sass-build@v0.2.2
        with:
          source: styles/index.scss
          destination: /tmp/xprog-designsystem/css/theme.css

      - name: Compile SCSS Files
        uses: gha-utilities/sass-build@v0.2.2
        with:
          source: styles/router.scss
          destination: /tmp/xprog-designsystem/css/router.css
          
      - name: Build
        run: npm run build
          
      - name: Slack notifcation theme
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ':small_blue_diamond: Build SCSS theme'
          icon_emoji: 'warning'
          text: Build SCSS theme ${{ job.status }}
          fields: commit, message, author
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack }}
        if: ${{ failure() }}
